excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage

function_body_length:
  warning: 150
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

force_cast: warning

cyclomatic_complexity: 15

disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - type_name
  - identifier_name
  
