platform :ios, '15.0'

target 'AppStoreReproduction' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'Reusable'
  pod 'SnapKit'
  pod 'SwiftFormat/CLI'
  pod 'SwiftGen'
  pod 'SwiftLint'
  pod 'Swinject'
end
